spring:
  datasource:
    username: codelex
    password: codelex
    url: jdbc:postgresql://localhost:5432/flight_planner
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml

flight-planner:
  store-type: database

apixu:
  api-url: https://api.apixu.com
  api-key: 00ab253837da498b9bc150014190903&q